In [5]:
import numpy as np
y = np.array([1,2,3,4])
j = np.array([5.5,6.6,6.9,7.7])
np.add(y,j)

array([ 6.5,  8.6,  9.9, 11.7])

In [8]:
import numpy as np
y = np.array([1,2,3,4])
j = np.array([5.5,6.6,6.9,7.7])
np.subtract(y,j)

array([-4.5, -4.6, -3.9, -3.7])

In [9]:
import numpy as np
y = np.array([1,2,3,4])
j = np.array([5.5,6.6,6.9,7.7])
np.multiply(y,j)

array([ 5.5, 13.2, 20.7, 30.8])

In [10]:
import numpy as np
y = np.array([1,2,3,4])
j = np.array([5.5,6.6,6.9,7.7])
np. divide(y,j)

array([0.18181818, 0.3030303 , 0.43478261, 0.51948052])

In [11]:
import numpy as np
y = np.array([[1,2],(3,4)])
np.sqrt(y)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

In [8]:
import numpy as np
y = np.array([[1,2],(3,4)])
np.min(y,axis=0)

array([1, 2])

In [9]:
import numpy as np
y = np.array([[1,2],(3,4)])
np.min(y,axis=1)

array([1, 3])

In [18]:
import numpy as np
y = np.array([[1,2],(3,4)])
np.power( y,3)

array([[ 1,  8],
       [27, 64]], dtype=int32)

In [21]:
import numpy as np
y = np.array([[1,2],(3,4)])
j= np.array([[2,3],[3,6]])
np.multiply( y,j)

array([[ 2,  6],
       [ 9, 24]])

In [11]:
import numpy as np
y = np.array([[1,2],(3,4)])
(np.max(y,axis=0))

array([3, 4])

In [10]:
import numpy as np
y = np.array([[1,2],(3,4)])
(np.max(y,axis=1))

array([2, 4])

In [12]:
import numpy as np
y = np.array([[1,2],(3,4)])
np.exp (y)

array([[ 2.71828183,  7.3890561 ],
       [20.08553692, 54.59815003]])

In [16]:
import numpy as np
y= np.array([[1,2],(3,4)])
y.mean()

2.5

In [17]:
import numpy as np
y= np.array([[1,2],(3,4)])
y.std()

1.118033988749895

In [19]:
import numpy as np
y= np.array([[1,2],(3,4)])
np.median(y)

2.5